version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: gradle test
      - run:
          name: "gradle build"
          command: gradle build
      - run:
          name: "docker_deploy"
          command: |
            docker build -t alertjjm/cicd-demo:$TAG .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push alertjjm/cicd-demo:$CIRCLE_BUILD_NUM
      - persist_to_workspace:
          root: ~/repo
          paths:
            - result.zip
      - store_artifacts:
          path: ~/repo/result.zip
          destination: build